### ISSUE TITLE
CHAP-01/F5-12E pluggable heating actuator not switching

### ISSUE THREAD

**Issue by oyvindth** [karloygard/xcomfortd-go#25]
I have just bought a CHAP-01/F5-12E puggable heating actuator. When added to HA, it shows up as a heating actuator, and if controlled by MRF, the status updates in HA, but no ems shows. If trying to controll from HA, nothing happens with the actuator have tried bout lovelace and MQTT.publish. 
Is this because it is not Supported? or is it another snag. 
All other connected devises works fine.

**Comment by karloygard** [comment]
That device is barely supported by the code. I don't have a heating actuator myself, so it's not completely trivial to fix that.

**Comment by oyvindth** [comment]
By your name, I guess you are located in Norway, if it would help, I am more than willing to lend you the devise if it would help with integrating heating actuators. 
As I understand the unit, it requires actual temp, and desired temp to work. If you find a way to send those messages to the unit, maby an automation could handle the cyclic sending of the data?

**Comment by karloygard** [comment]
That would likely speed up development substantially. I live in Oslo, but as most Norwegians, I'm on vacation at the moment. We can touch base in the beginning of August and take it from there?

**Comment by oyvindth** [comment]
Sounds like a great plan. I drive through Oslo on a regular basis, or i could send it to you by Mail. Enjoy the rest of fellesferien.

**Comment by oyvindth** [comment]
Hi again. I am back from vacation. Easiest for me would be to send you the device pr mail, but I understand if you are not to keen on posting personal data here. Any chance I could PM you on Facebook Messenger.

**Comment by karloygard** [comment]
👍🏻 Find me there, full name Karl Anders Øygard.

**Comment by karloygard** [comment]
> I am stil not able to sent the current_temperature to the actuator however.

I'll fiddle with it a little myself and see if I get any further.

>The number.current_temperature entity is not showing anymore after the last update, might be a problem on my end thoug. I havent tried to rebuild the xcomfort addon yet. and I am not able to figure out what MQTT topic to send the current temperature to. My plan was to create an automation that simply forwards the RCT temp with a MQTT publich command to the actuator, but I am not sure to what topic to send the temperature to.

The MQTT topic for current temperature is `xcomfort/{dp}/set/current`, for example `xcomfort/50/set/current`.

> When sending a desired temperature to the actuator, I can see the MQTT transmission, but the confirmation from the actuator is only showed in MRF. Not showing up in MQTT for some reason. Don't know if it is relevant.

Currently, no confirmation is sent via MQTT, so this is correct.

**Comment by karloygard** [comment]
The following automation does the trick:
```
- alias: Copy temperature every minute                                                                                                                                                                
  trigger:                                                                                                                                                                                            
  - platform: time_pattern                                                                                                                                                                            
    minutes: "/1"                                                                                                                                                                                     
  action:                                                                                                                                                                                             
  - service: number.set_value                                                                                                                                                                         
    target:                                                                                                                                                                                           
      entity_id: number.current_temperature                                                                                                                                                           
    data_template:                                                                                                                                                                                    
      value: "{{ states('sensor.romkontroller') }}"                                                                                                                                                   
```
Runs every minute, which is maybe a little aggressive.
